branches: main

variables:
  - &file Containerfile
  - &repo codeberg.org/xtex-vnet/mekbuda

pipeline:
  container-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      dockerfile: *file
      platforms: linux/arm64/v8,linux/amd64
      repo: *repo
      registry: codeberg.org
      tags: latest
      username: ${CI_REPO_OWNER}
      password:
        from_secret: oci_token
    when:
      event: push
