FROM docker.io/library/php:8.1-fpm-alpine

ARG MAJOR_VERSION=1.39
ARG VERSION=1.39.3

RUN apk add --no-cache git imagemagick python3

RUN apk add --no-cache --virtual .build-deps $PHPIZE_DEPS icu-dev oniguruma-dev
RUN docker-php-ext-install -j8 calendar intl mbstring mysqli opcache
RUN pecl install APCu-5.1.21; docker-php-ext-enable apcu; rm -r /tmp/pear
RUN runDeps="$( \
    scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions \
    | tr ',' '\n' \
    | sort -u \
    | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
    )"; \
    apk add --virtual .mediawiki-phpext-rundeps $runDeps
RUN apk del .build-deps

RUN { \
    echo 'opcache.memory_consumption=128'; \
    echo 'opcache.interned_strings_buffer=8'; \
    echo 'opcache.max_accelerated_files=4000'; \
    echo 'opcache.revalidate_freq=60'; \
    echo 'opcache.fast_shutdown=1'; \
    } > /usr/local/etc/php/conf.d/opcache-recommended.ini

RUN mkdir -p /var/www/data; chown -R www-data:www-data /var/www/data

LABEL org.opencontainers.image.title=MediaWiki
LABEL org.opencontainers.image.vendor="XV-NET"
LABEL org.opencontainers.image.source="https://codeberg.org/xvnet/containers"

ADD https://releases.wikimedia.org/mediawiki/$MAJOR_VERSION/mediawiki-$VERSION.tar.gz /mw.tar.gz
RUN tar -x --strip-components=1 -f /mw.tar.gz
RUN rm /mw.tar.gz
RUN chown -R www-data:www-data extensions skins cache images

ENTRYPOINT [ "/usr/local/sbin/php-fpm" ]
