FROM docker.io/library/mediawiki:stable-fpm-alpine

LABEL org.opencontainers.image.title=MediaWiki
LABEL org.opencontainers.image.vendor="XV-NET"
LABEL org.opencontainers.image.source="https://codeberg.org/xvnet/containers"

RUN apk add --no-cache diffutils
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
RUN apk add --no-cache libpq libpq-dev
RUN docker-php-ext-install pgsql pdo_pgsql
