FROM docker.io/library/alpine AS builder

RUN apk add bash curl ldns-tools drill jq make grep sed coreutils perl
ADD . /bld
WORKDIR /bld
RUN make -j4

FROM scratch
COPY --from=builder /bld/out/root.zone.signed /root.zone
COPY --from=builder /bld/out/dnssec-zsk.key /root.zsk.key

LABEL org.opencontainers.image.source="https://codeberg.org/xvnet/atremis"
LABEL org.opencontainers.image.title="XVN Root Zone Files"
LABEL org.opencontainers.image.url="https://www.iana.org/domains/root"
LABEL org.opencontainers.image.vendor="XV-NET"
