#!/usr/bin/env bash
set -euo pipefail

pushd ..
git submodule update --init --recursive
hugo --enableGitInfo --minify
cp -R public /srv/http/xtex1
rm -rf /srv/http/xtex
mv /srv/http/xtex1 /srv/http/xtex
popd
