ARG VERSION
FROM docker.io/binwiederhier/ntfy:v$VERSION as bld

FROM docker.io/library/alpine

RUN apk add --no-cache tzdata
COPY --from=bld /usr/bin/ntfy /usr/bin

ENTRYPOINT ["ntfy"]
CMD [ "serve" ]

LABEL org.opencontainers.image.licenses="Apache-2.0 OR GPL-2.0-or-later"
LABEL org.opencontainers.image.source="https://codeberg.org/xens/atremis"
LABEL org.opencontainers.image.title="ntfy"
LABEL org.opencontainers.image.url="https://ntfy.sh/"
LABEL org.opencontainers.image.vendor="Xensor V Project"
LABEL org.opencontainers.image.documentation="https://docs.ntfy.sh/"
