#!/usr/bin/bash
# Called from Justfile for sending patches for review
set -euo pipefail

die() {
	echo "$*"
	exit 1
}

topicBranch="$(git rev-parse --abbrev-ref HEAD)"
topicHead="$(git rev-parse HEAD)"
[[ "$topicBranch" != "HEAD" ]] || die "You are not on a branch."

baseRef="$(git config branch."$topicBranch".merge)"
baseRemote="$(git config branch."$topicBranch".remote)"
baseBranch="$(git rev-parse --abbrev-ref "$baseRef")"

readarray -t topicCommits < <(git log "$baseRemote"/"$baseBranch"..."$topicHead" --format='%H' --reverse)

for commit in "${topicCommits[@]}"; do
	abbrevCommit="$(git log -1 --format='%h' "$commit")"
	subject="$(git log -1 --format='%s' "$commit")"
	bug="$(git log -1 --format='%(trailers:key=Bug,only,valueonly,separator=%x2C)' "$commit" | cut -d',' -f1)"
	changeId="$(git log -1 --format='%(trailers:key=Change-Id,only,valueonly,separator=%x2C)' "$commit" | cut -d',' -f1)"
	[[ -n "$changeId" ]] || die "Change-Id is missing for $commit"

	topic="change/$changeId"

	echo "-----
[$topicBranch $abbrevCommit] $subject
-> $baseRemote/$baseBranch
Bug: ${bug:--}
Change-Id: $changeId
-----"

	git push "$baseRemote" "$commit":refs/for/"$baseBranch" \
		-o topic="$topic" \
		-o title="$subject" \
		-o force-push=true || true
done
