#!/usr/bin/env bash

sudo pacman -Sy archlinux-keyring
sudo pacman -Syuu
sudo pacman -S fish

sudo usermod -a -G root "$(whoami)"
[[ -e "/srv" ]] || sudo mkdir /srv
sudo chmod g+w -R /srv /usr/local/bin

sudo useradd -G root -m -r -U -s /usr/bin/fish services
sudo usermod -a -G services "$(whoami)"

cd /srv || exit
sudo -u services git clone --depth 1 https://codeberg.org/xvnet/atremis.git
git config --global --add safe.directory /srv/atremis
sudo git config --global --add safe.directory /srv/atremis

cd atremis || exit
./atre pull

which atre
sudo reboot
