#!/usr/bin/env bash
set -xe

# Update system
initPkgs="pacman -Sy archlinux-keyring; pacman -Syuu; pacman -S bash fish make coreutils sudo"
if command -v sudo >/dev/null; then
	sudo "$initPkgs"
else
	su -c "$initPkgs"
fi

# Configure system basics
sudo usermod -a -G root "$(whoami)"

# Fetch atremis
if ! [[ -e "/srv/atremis" ]]; then
	sudo mkdir -p /srv
	sudo git clone --depth 1 --recurse-submodules --shallow-submodules --single-branch https://codeberg.org/xvnet/atremis.git
	sudo chmod -R a+r atremis
fi

if ! [[ -e "/srv/secrets" ]]; then
	sudo mkdir /srv/secrets
	sudo chmod -R 0772 /srv/secrets
fi

# Update
(
	cd /srv/atremis
	./atre pull
	./atre update
)

# Validation
command -v atre

echo "===== SUCCEED ====="
echo "PRESS ANY KEY TO RESTART OR CTRL+C TO ABORT"
read -n1 -r && sudo systemctl restart
