use chrono::DateTime;
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
	async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
		manager
			.create_table(
				Table::create()
					.table(Page::Table)
					.if_not_exists()
					.col(
						ColumnDef::new(Page::Id)
							.uuid()
							.not_null()
							.primary_key()
							.unique_key(),
					)
					.col(ColumnDef::new(Page::Lang).string_len(8).not_null())
					.col(ColumnDef::new(Page::Title).string_len(255).not_null())
					.col(
						ColumnDef::new(Page::LastChecked)
							.timestamp()
							.default(DateTime::UNIX_EPOCH)
							.not_null(),
					)
					.col(
						ColumnDef::new(Page::NeedCheck)
							.timestamp()
							.null(),
					)
					.col(
						ColumnDef::new(Page::Issues)
							.unsigned()
							.default(0)
							.not_null(),
					)
					.col(
						ColumnDef::new(Page::Suggests)
							.unsigned()
							.default(0)
							.not_null(),
					)
					.to_owned(),
			)
			.await?;
		manager
			.create_index(
				Index::create()
					.name("pages_id")
					.table(Page::Table)
					.if_not_exists()
					.col(Page::Id)
					.unique()
					.index_type(IndexType::BTree)
					.to_owned(),
			)
			.await?;
		manager
			.create_index(
				Index::create()
					.name("pages_with_issues")
					.table(Page::Table)
					.if_not_exists()
					.col(Page::Issues)
					.to_owned(),
			)
			.await?;
		manager
			.create_index(
				Index::create()
					.name("pages_with_suggests")
					.table(Page::Table)
					.if_not_exists()
					.col(Page::Suggests)
					.to_owned(),
			)
			.await?;
		manager
			.create_index(
				Index::create()
					.name("pages_need_check")
					.table(Page::Table)
					.if_not_exists()
					.col(Page::NeedCheck)
					.to_owned(),
			)
			.await?;
		manager
			.create_index(
				Index::create()
					.name("pages_by_name")
					.table(Page::Table)
					.if_not_exists()
					.col(Page::Lang)
					.col(Page::Title)
					.unique()
					.index_type(IndexType::BTree)
					.to_owned(),
			)
			.await?;
		Ok(())
	}

	async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
		manager
			.drop_index(Index::drop().table(Page::Table).name("pages_id").to_owned())
			.await?;
		manager
			.drop_index(Index::drop().table(Page::Table).name("pages_with_issues").to_owned())
			.await?;
		manager
			.drop_index(Index::drop().table(Page::Table).name("pages_with_suggests").to_owned())
			.await?;
		manager
			.drop_index(Index::drop().table(Page::Table).name("pages_need_check").to_owned())
			.await?;
		manager
			.drop_index(Index::drop().table(Page::Table).name("pages_by_name").to_owned())
			.await?;
		manager
			.drop_table(Table::drop().table(Page::Table).to_owned())
			.await?;
		Ok(())
	}
}

#[derive(DeriveIden)]
enum Page {
	Table,
	Id,
	Lang,
	Title,
	LastChecked,
	NeedCheck,
	Issues,
	Suggests,
}
