steps:
    - name: build
      image: woodpeckerci/plugin-docker-buildx
      settings:
          platforms: linux/amd64,linux/arm64/v8
          repo: codeberg.org/${CI_REPO_OWNER}/x-caddy
          registry: codeberg.org
          username: ${CI_REPO_OWNER}
          password:
              from_secret: codeberg_token
          context: services/caddy
          dockerfile: services/caddy/Containerfile
    - name: send-ntfy
      image: alpine
      secrets: [ntfy_token]
      when:
          - status: [success, failure]
      commands:
          - ./scripts/pkgs/send-log.sh
when:
    - event: push
      branch: main
      path:
          include:
              [".woodpecker/build-caddy.yaml", "services/caddy/Containerfile"]
    - event: cron
      cron: build-pkgs
    - event: manual
      evaluate: 'TARGET == "all" || TARGET == "caddy"'
