FROM docker.io/library/alpine AS builder

RUN apk add bash ldns-tools make coreutils dnscontrol
ADD zones /bld/zones
ADD . /bld/dnscontrol
WORKDIR /bld
RUN make -C dnscontrol -j4

RUN . dnscontrol/.env.sh; dnscontrol preview