#!/usr/bin/bash
set -euo pipefail

die() {
	echo "$*"
	exit 1
}

[[ "$#" == 1 ]] || die "$0 requires one argument."

if git rev-parse --verify HEAD >/dev/null 2>&1; then
	refhash="$(git rev-parse HEAD)"
else
	refhash="$(git hash-object -t tree /dev/null)"
fi
random="$({
	git var GIT_COMMITTER_IDENT
	echo "$refhash"
	cat "$1"
} | git hash-object --stdin)"
temp="$1.tmp.$random"
trap 'rm -f "${temp}.1" "${temp}.2"' EXIT

sed -e '/>8/q' "$1" | git stripspace --strip-comments >"${temp}.1"

# skip empty messages
if [[ "$(wc -l <"${temp}.1")" == 0 ]]; then
	exit 0
fi

if git interpret-trailers --parse <"${temp}.1" | grep -q "^Change-Id: .*$"; then
	exit 0
fi

git interpret-trailers \
	--where before \
	--trailer Change-Id="I$random" <"${temp}.1" >"${temp}.2"

mv "${temp}.2" "$1"
